#index:
#    path: /
#    controller: App\Controller\DefaultController::index


todoList:
  path: /
  controller: App\Controller\MainController::todoList

viewTodoItem:
  path: /todo/{id}
  controller: App\Controller\TodoController:viewTodo