#index:
#    path: /
#    controller: App\Controller\DefaultController::index

entry:
  path: /
  controller: App\Controller\EntryController::entry

todoList:
  path: /todoList
  controller: App\Controller\TodoController::todoList

viewTodoItem:
  path: /todoList/todo/{id}
  controller: App\Controller\TodoController::viewTodo
  requirements:
    id: '\d+'

todoAddNew:
  path: /todoList/new
  controller: App\Controller\TodoController:todoAddNew

todoUpdateSuccess:
  path: /todoList/todo/{id}/updateSuccess
  controller: App\Controller\TodoController::todoUpdated
  requirements:
    id: '\d+'

todoDeleteSuccess:
  path: /todoList/todo/{id}/deleteSuccess
  controller: App\Controller\TodoController::todoDeleted
  requirements:
    id: '\d+'

todoToggleIsDone:
  path: /todoList/todo/{id}/toggleIsDone
  controller: App\Controller\TodoController::todoToggleIsDone
  methods:    [POST]
  requirements:
    id: '\d+'

login:
  path: /login
