#index:
#    path: /
#    controller: App\Controller\DefaultController::index


todoList:
  path: /
  controller: App\Controller\TodoController::todoList

viewTodoItem:
  path: /todo/{id}
  controller: App\Controller\TodoController::viewTodo

todoAddNew:
  path: todoNew
  controller: App\Controller\TodoController:todoAddNew

todoUpdateSuccess:
  path: /todo/{id}/updateSuccess
  controller: App\Controller\TodoController::todoUpdated
  requirements:
    id: '\d+'

todoDeleteSuccess:
  path: /todo/{id}/deleteSuccess
  controller: App\Controller\TodoController::todoDeleted
  requirements:
    id: '\d+'

todoToggleIsDone:
  path: /todo/{id}/toggleIsDone
  controller: App\Controller\TodoController::todoToggleIsDone
  methods:    [POST]
  requirements:
    id: '\d+'

